minimumReleaseAgeExcludePrune: true

trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar@4.0.3

shellEmulator: true

allowBuilds:
  cpu-features: true
  esbuild: true
  protobufjs: true
  sharp: true
  ssh2: true
